from django.conf.urls.defaults import *
import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name="dj_index"),
                       url(r'^status/$', views.status, name="dj_status"),
                       url(r'^jump/(?P<id>\d+)/$', views.jump, name="dj_jump"),
                       url(r'^next/$', views.next, name="dj_next"),
                       url(r'^prev/$', views.prev, name="dj_previous"),
                       url(r'^play/$', views.play, name="dj_play"),
                       url(r'^pause/$', views.pause, name="dj_pause"),
                       url(r'^stop/$', views.stop, name="dj_stop"),
                       url(r'^artists/$', views.list_artists, name="dj_list_artists"),
                       url(r'^albums/(?P<artist>.*)/$', views.list_albums, name="dj_list_albums"),
                       url(r'^titles/(?P<artist>.*)/(?P<album>.*)/$', views.list_titles, name="dj_list_titles"),
                       url(r'^add/artist/(?P<artist>.*)/$', views.artist_add, name="dj_add_artist"),
                       url(r'^add/album/(?P<artist>.*)/(?P<album>.*)/$', views.album_add, name="dj_add_album"),
                       url(r'^add/title/(?P<id>\d+)/$', views.add_title, name="dj_add_title"),
                       url(r'^remove/(?P<id>\d+)/$', views.remove, name="dj_remove"),
                       url(r'^move/$', views.move_entry, name="dj_move_entry"),
                       url(r'^move/up/(?P<pos>\d+)/$', views.move_entry_up, name="dj_move_entry_up"),
                       url(r'^move/down/(?P<pos>\d+)/$', views.move_entry_down, name="dj_move_entry_down"),
                       url(r'^clear/$', views.clear_playlist, name="dj_clear_playlist"),
                       url(r'^load/(?P<playlist>.*)/$', views.load_playlist, name="dj_load_playlist"),
                       url(r'^playlist/list/$', views.get_playlist_list, name="dj_list_playlists"),
                       url(r'^playlist/create/$', views.create_playlist, name="dj_create_playlist"),
                       url(r'^playlist/remove/$', views.remove_playlist, name="dj_remove_playlist"),
                       url(r'^playlist/shuffle/$', views.shuffle_playlist, name="dj_shuffle_playlist"),
                       url(r'^playlist/export/$', views.export_playlist, name="dj_export_playlist"),
                       url(r'^search/$', views.search, name="dj_search"),
                       url(r'^search/artist/$', views.search_artist, name="dj_search_artist"),
                       url(r'^search/album/$', views.search_album, name="dj_search_album"),
                       url(r'^search/title/$', views.search_title, name="dj_search_title"),
                       url(r'^info/title/(?P<id>\d+)/$', views.show_info, name="dj_show_info"),
                       url(r'^volume/up/(?P<vol_add>\d+)/$', views.volume_up, name="dj_volume_up"),
                       url(r'^volume/down/(?P<vol_add>\d+)/$', views.volume_down, name="dj_volume_down"),
                      )
